version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-url_shortener}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-url_shortener_db}

    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url_shortener_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3000}
      BASE_URL: ${BASE_URL}
      NODE_ENV: ${NODE_ENV:-production}
    networks:
      - url_shortener_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:

networks:
  url_shortener_network:
    driver: bridge
